---
title: "1001 R_tidyverse"
author: "reference: teacher's handout"
date: "2021/9/30"
output: html_document
---

### tidyverse
```{r}
#set working directory
setwd("D:/Chang-web")
#load the rda file
load(file = "carsale.Rda")

# 原本R的寫法
set.seed(1) # 把隨機取值存在某個空間，括弧內的數字任意
x = rnorm(100)
y = abs(x)
hist(y)

# with %>%:
#install.packages("tidyverse")
library(tidyverse)
library(magrittr)
rnorm(100) %>%
  abs() %>%
  hist()


# car sale 例子
mydata %>%
  dim()      # dim(mydata)

mydata$city %>%
  summary()   # summary(column)

mydata$maker %>%
  str()   # data information

mydata %>%
  filter(maker=="toyota") %>%
  select(id, maker, price) %>% 
  head()

# 用小一點的資料試試
mydata2 <- filter(mydata, !is.na(price), maker=="volvo"| maker== "tesla"| maker=="lexus" ) %>%
  select( maker,price,year,type )  

mydata %>% 
  filter(!is.na(price), maker=="volvo"| maker== "tesla"| maker=="lexus" ) %>%
  select( Pay = price, Car = type ) %>% #can also change var name
  head()

mydata2 %>%
  select( type, price, everything() ) %>% #change the order of variables
  head()
  
mydata2 %>%
  filter( price >= 15000 & maker =="tesla" )   #subset
  
mydata2 %>%
  filter( maker =="tesla" ) %>%  
  select( year ) 

mydata2 %>%
  summarise(avg = mean(price, na.rm = TRUE) )

mydata2 %>%
  group_by( maker ) %>%
  summarise( mean(price, na.rm = TRUE) )

mydata2 %>%
  group_by( maker ) %>%
  summarise( count = n(), # 多少個
             avg_price = mean(price),
             avg_year = mean(year[price>10000]),
             sd_price = sd(price)
            )

mydata2 %>%
  mutate( new_price = price*0.5 ) %>%  # create a new column
  head()
  

mydata2 %>%
  arrange( price ) %>% #sort
  head()

mydata2 %>%
  arrange( desc(price) ) %>%
  head()

mydata2 %>%
  arrange( price, year ) %>% #sort
  head()

mydata2 %>%
  filter(price >= 15000 & maker =="lexus") %>%  
  tally()  #how many符合條件的資料筆數

mydata2 %>%
  filter( price == max(price) ) %>% 
  select( maker, year, price )


mydata2 %>%
  group_by( maker,type ) %>%
  tally()

mydata2 %>% 
  count( maker, type ) %>%  
  ggplot( mapping = aes(x = maker, y = type) ) +
  geom_tile( mapping = aes(fill = n) )

# scatter plot in quick plot
mydata2 %>% 
  qplot( price,year,col=maker, data=. ) 

# histogram in quick plot
mydata2 %>% 
  qplot( price, geom="histogram", data=., bins=5 ) 

# scatter plot in ggplot
mydata2 %>% 
  ggplot(mapping = aes(x = year, y = price)) + 
  geom_point()

# histogram in ggplot
mydata2 %>% 
  ggplot(aes(x = price)) + 
  geom_histogram(binwidth = 10000 )

mydata2 %>%
  sample_frac(0.005) # sample 0.5% 的資料

set.seed(99)
mydata2 %>%
  sample_n(5) # 用set.seed固定sample的資料

#tidyr
table1 # 理想的資料形式

table2 # 不理想的資料形式
# spread()把儲存在同一個 column 的多個變數分開
table2 %>% spread(type, count) # 把type分開，用count值帶入
table2 %>%
  spread(key = type,
         value = count,
         sep = '_') # 欄位名稱加入'_'

table3 # 不理想的資料形式
# 用seperate將一行中的數值分解成多行
table3 %>% separate(rate, into=c("cases", "population"), sep = "/") #should not be character 
table3 %>% separate(rate, into=c("cases", "population"), sep = "/", convert = TRUE) # 轉成數值形式

# gather() :gather column into key-value pairs
table4a %>% gather(key = "year", value = "cases", `1999`:`2000`) -> tidy4a

tidy4a <- table4a %>% gather(key = "year",  # 新變數欄位
                             value = "cases", # 新變數變數值儲存欄位名稱
                             `1999`:`2000`) # 被蒐集起來變成新變數的 columns
tidy4a

tidy4b <- table4b %>% gather(year, population, `1999`:`2000`) 
tidy4b

left_join(tidy4a, tidy4b) # 往左合併

# unite():將被分存在不同 columns 中的觀測值合併成新的欄位 
# 將century和year合併成Year，sep=""表示中間沒有空格
table5 %>% unite(Year, # 合併後的新column
                 century, year, #原欄位名稱
                 sep="") %>%  
  separate(rate, into=c("cases", "population"), sep = "/", convert=TRUE)

```


### join
```{r}
setwd("D:/Chang-web")
#library(readr)
student <- read_csv("lec2_data1.csv")
moodle <- read_csv("lec2_data2.csv")
course <- read_csv("lec2_data3.csv")

student %>% inner_join(moodle) 

moodle2 <- moodle[c(1:3),]
student %>% inner_join(moodle2)  # 有出現的才合併
student %>% full_join(moodle2) # 全都合併，非交集值以NA取代

student2 <- student[-6,]
student2 %>% left_join(moodle2) 
student2 %>% right_join(moodle2) 

student %>% 
  left_join(moodle, by = "moodle_id") %>%  # 如果有很多key，可指定(by)
  left_join(course) 
```

### review R basic
```{r}
class(mydata[,13]) # data type in a certain column
head(sapply(mydata, class)) 
summary(mydata[,13]) 
names(mydata) # colnames(mydata)
```

#### missing values
```{r}
noNAtype  <- mydata[which(mydata$type != "NA"),] #which()找type裡的NA值，並去掉type有NA的
noNAdata <- na.omit(mydata) # 去掉所有NA
summary(noNAdata$city) # table(noNAdata$city) 
levels(noNAdata$city) 
```

#### find the most expensive car
```{r}
max(mydata$price, na.rm=T)
which.max(mydata$price) # 第8140筆資料是最貴的車
mydata[ which.max(mydata$price), ]$maker # 查看車的製造商
mydata[ which.max(mydata$price), ]$header 
```

#### replacing the extreme value
```{r}
summary(mydata$price)
mydata[which(mydata$price==max(mydata$price,na.rm=T)),]$price = median(c(6000,30000)) # 用中位數取代
mydata[which.max(mydata$price),]$header 
mydata[which.max(mydata$price),]$price
head(sort(mydata$price,decreasing=T))
```

#### graph
```{r}
# 查看類別型變數
head(table(mydata$maker)) 
plot(mydata$long,mydata$lat) 

library(lattice)
xyplot(lat ~ long, mydata)
xyplot(lat ~ long | type, mydata) # | : given ...


#install.packages("ggplot2")
library(ggplot2)
ggplot(mydata, aes(x = long, y = lat)) +
  geom_point()+
  theme_classic()

ggplot(mydata, aes(x = long, y = lat)) +
  geom_point() +
  facet_wrap(~ type, ncol = 3)

```

#### subset
```{r}
bmw_df <- subset(mydata, maker=="bmw") # 從mydata抓取maker都是BMW的車
head(bmw_df$id)
# 設定條件，選取變數
head(subset(bmw_df, price > 40000, select = c(price, maker,type))) 
head(subset(bmw_df, price > 40000 & type=='SUV', select = c(price, maker, type)))
```